# Generated by Django 3.2.8 on 2021-12-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20211202_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='connect_with_auth',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='http://127.0.0.1:8000/api/', editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(default='http://127.0.0.1:8000/api/', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(default='http://127.0.0.1:8000/api/', max_length=500),
        ),
    ]
