# Generated by Django 3.2.8 on 2021-12-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='backend.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='https://cmput-404-social-distribution.herokuapp.com/api/', editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(default='https://cmput-404-social-distribution.herokuapp.com/api/', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(default='https://cmput-404-social-distribution.herokuapp.com/api/', max_length=500),
        ),
    ]
